version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - mynetwork
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - mynetwork
  database:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=duty
    volumes:
      - /var/lib/dutydb/pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
