# Database Configuration
database:
  host: database
  port: 5432q
  name: duty
  user: root
  password: password

# Server Configuration
server:
  port: 8080
  host: 0.0.0.0

# token secret
token:
  secret: secretwalajfljvlejlvkljalbjvssss
  expiration_duration: 1h
