FROM node:18.9.0

WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . .

# Build the React app
RUN npm run build

# Install serve module
RUN npm install -g serve

# Expose the default serve port (optional)
EXPOSE 3000

# Set the command to run the app with serve
CMD ["serve", "-s", "build"]
